<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MacBook-Pro-de-M.local" name="businessLogic.TopicDAOTest" tests="2" failures="1" timestamp="13 Apr 2021 05:08:56 GMT" time="1.709" errors="0">
  <testcase name="testSave on testSave(businessLogic.TopicDAOTest)" time="1.298" classname="businessLogic.TopicDAOTest">
    <failure type="java.lang.IllegalStateException" message="Parameter index ">
      <![CDATA[java.lang.IllegalStateException: Parameter index 
	at businessLogic.TopicDAO.save(TopicDAO.java:42)
	at businessLogic.TopicDAOTest.testSave(TopicDAOTest.java:19)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
Caused by: java.sql.SQLException: Parameter index out of range (5 > number of parameters, which is 4).
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ClientPreparedStatement.checkBounds(ClientPreparedStatement.java:1372)
	at com.mysql.cj.jdbc.ClientPreparedStatement.getCoreParameterIndex(ClientPreparedStatement.java:1385)
	at com.mysql.cj.jdbc.ClientPreparedStatement.setString(ClientPreparedStatement.java:1752)
	at businessLogic.TopicDAO.save(TopicDAO.java:35)
	... 37 more
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testSave on testSave(businessLogic.TopicDAOTest) -->
  <testcase name="testGetAgendaTopics on testGetAgendaTopics(businessLogic.TopicDAOTest)" time="0.06" classname="businessLogic.TopicDAOTest"/>
</testsuite> <!-- businessLogic.TopicDAOTest -->
